export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_DECREMENT_POINTS="USER_DECREMENT_POINTS"
export const USER_INCREMENT_POINTS="USER_INCREMENT_POINTS"

export const USER_CLEAR_CACHE_REQUEST="USER_CLEAR_CACHE_REQUEST"
export const USER_CLEAR_CACHE_SUCCESS="USER_CLEAR_CACHE_SUCCESS"
export const USER_CLEAR_CACHE_ERROR="USER_CLEAR_CACHE_ERROR"